name: Run My First Workflow
on: 
  push: 
    branches:  [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  workflow_dispatch: 
  schedule:
    - cron: "15 06 * * 6"
jobs:
  SayHello:
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo "Hello all!"
      - name: Checkout
        uses: actions/checkout@v7.0.0
